import { Observable } from 'rxjs';

import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { environment } from 'src/environments/environment';


@Injectable({
  providedIn: 'root'
})
export class RefundTableService {
  getPath="SEND_DATA"
  data = [
    {
        "PSS_NO": 5480233502,
        "SIP_TRH": "2022-05-10",
        "FTR_TRH": "2022-05-10",
        "PIS_NO": 5480233502,
        "IADE_TRH": "2022-05-10",
        "MUSAD": "TEST TEST",
        "BELGE_TOPL": 27.98,
        "BELGE_TOPL_PB": "TRY",
        "ODEME_TIP": "KKART",
        "ODEME_TIP_T": "Kredi Kartı",
        "BANKA_KODU": "0062",
        "BANKA_TANIM": "TÜRKİYE GARANTİ BANKASI A.Ş.",
        "IADE_TUTAR": 27.98,
        "IADE_TUTAR_PB": "TRY",
        "PC_TUTAR": 0,
        "PC_TUTAR_PB": "",
        "HCEKI": "",
        "KKP_TUTAR": 0,
        "KKP_TUTAR_PB": "",
        "ONAY_KOD": "851935-6248-authCode",
        "ISLENEN_POS": "",
        "VBTYP": "",
        "STATU": 5,
        "STATU_T": "Müşteriye Para İadesi Yapılacak!",
        "SPRS_ONAY": "851935-6248-authCode"
    },
    {
        "PSS_NO": 5563540824,
        "SIP_TRH": "2022-05-11",
        "FTR_TRH": "2022-05-11",
        "PIS_NO": 5563540824,
        "IADE_TRH": "2022-05-11",
        "MUSAD": "şevval durmaz",
        "BELGE_TOPL": 56.89,
        "BELGE_TOPL_PB": "TRY",
        "ODEME_TIP": "HCEKI",
        "ODEME_TIP_T": "Hediye Çeki",
        "BANKA_KODU": "0000",
        "BANKA_TANIM": "",
        "IADE_TUTAR": 0,
        "IADE_TUTAR_PB": "",
        "PC_TUTAR": 56.89,
        "PC_TUTAR_PB": "TRY",
        "HCEKI": "PC0001DW6J87A820F",
        "KKP_TUTAR": 0,
        "KKP_TUTAR_PB": "",
        "ONAY_KOD": "",
        "ISLENEN_POS": "",
        "VBTYP": "H",
        "STATU": 5,
        "STATU_T": "Müşteriye Para İadesi Yapılacak!",
        "SPRS_ONAY": ""
    },
    {
        "PSS_NO": 5563540826,
        "SIP_TRH": "2022-05-11",
        "FTR_TRH": "2022-05-11",
        "PIS_NO": 5563540826,
        "IADE_TRH": "2022-05-11",
        "MUSAD": "şevval durmaz",
        "BELGE_TOPL": 56.89,
        "BELGE_TOPL_PB": "TRY",
        "ODEME_TIP": "HCEKI",
        "ODEME_TIP_T": "Hediye Çeki",
        "BANKA_KODU": "0000",
        "BANKA_TANIM": "",
        "IADE_TUTAR": 0,
        "IADE_TUTAR_PB": "",
        "PC_TUTAR": 56.89,
        "PC_TUTAR_PB": "TRY",
        "HCEKI": "PC0001DW6J87A820F",
        "KKP_TUTAR": 0,
        "KKP_TUTAR_PB": "",
        "ONAY_KOD": "",
        "ISLENEN_POS": "",
        "VBTYP": "H",
        "STATU": 5,
        "STATU_T": "Müşteriye Para İadesi Yapılacak!",
        "SPRS_ONAY": ""
    },
    {
        "PSS_NO": 5563540830,
        "SIP_TRH": "2022-05-11",
        "FTR_TRH": "2022-05-11",
        "PIS_NO": 5563540830,
        "IADE_TRH": "2022-05-11",
        "MUSAD": "şevval durmaz",
        "BELGE_TOPL": 103.79,
        "BELGE_TOPL_PB": "TRY",
        "ODEME_TIP": "KKART",
        "ODEME_TIP_T": "Kredi Kartı",
        "BANKA_KODU": "0010",
        "BANKA_TANIM": "TÜRKİYE CUMHURİYETİ ZİRAAT BANKASI A.Ş.",
        "IADE_TUTAR": 83.79,
        "IADE_TUTAR_PB": "TRY",
        "PC_TUTAR": "20.00",
        "PC_TUTAR_PB": "TRY",
        "HCEKI": "PC0001DW6J87A820F",
        "KKP_TUTAR": 0,
        "KKP_TUTAR_PB": "",
        "ONAY_KOD": "894664-8232-authCode",
        "ISLENEN_POS": "",
        "VBTYP": "",
        "STATU": 5,
        "STATU_T": "Müşteriye Para İadesi Yapılacak!",
        "SPRS_ONAY": "894664-8232-authCode"
    },
    {
      "PSS_NO": 5563534913,
      "SIP_TRH": "2022-02-24",
      "FTR_TRH": "2022-02-24",
      "PIS_NO": 5563534913,
      "IADE_TRH": "2022-02-24",
      "MUSAD": "şevval durmaz",
      "BELGE_TOPL": 10.99,
      "BELGE_TOPL_PB": "TRY",
      "ODEME_TIP": "HCEKI",
      "ODEME_TIP_T": "Hediye Çeki",
      "BANKA_KODU": "0000",
      "BANKA_TANIM": "",
      "IADE_TUTAR": 0,
      "IADE_TUTAR_PB": "",
      "PC_TUTAR": 10.99,
      "PC_TUTAR_PB": "TRY",
      "HCEKI": "PC0001DW61M130D6A",
      "KKP_TUTAR": 0,
      "KKP_TUTAR_PB": "",
      "ONAY_KOD": "",
      "ISLENEN_POS": "",
      "VBTYP": "H",
      "STATU": 8,
      "STATU_T": "İade Ödeme Hatası",
      "SPRS_ONAY": ""
  },
  {
      "PSS_NO": 5440008808,
      "SIP_TRH": "2022-02-08",
      "FTR_TRH": "2022-02-08",
      "PIS_NO": 5440008808,
      "IADE_TRH": "2022-02-08",
      "MUSAD": "Ömer Tarık Arslantaş",
      "BELGE_TOPL": 40.89,
      "BELGE_TOPL_PB": "TRY",
      "ODEME_TIP": "KKART",
      "ODEME_TIP_T": "Kredi Kartı",
      "BANKA_KODU": "0046",
      "BANKA_TANIM": "AKBANK T.A.Ş.",
      "IADE_TUTAR": 40.89,
      "IADE_TUTAR_PB": "TRY",
      "PC_TUTAR": 0,
      "PC_TUTAR_PB": "",
      "HCEKI": "",
      "KKP_TUTAR": 0,
      "KKP_TUTAR_PB": "",
      "ONAY_KOD": "",
      "ISLENEN_POS": "",
      "VBTYP": "",
      "STATU": 8,
      "STATU_T": "İade Ödeme Hatası",
      "SPRS_ONAY": ""
  },
  {
      "PSS_NO": 5440010001,
      "SIP_TRH": "2022-02-21",
      "FTR_TRH": "2022-02-21",
      "PIS_NO": 5440010001,
      "IADE_TRH": "2022-02-21",
      "MUSAD": "Ömer Tarık Arslantaş",
      "BELGE_TOPL": 10.99,
      "BELGE_TOPL_PB": "TRY",
      "ODEME_TIP": "KKART",
      "ODEME_TIP_T": "Kredi Kartı",
      "BANKA_KODU": "0046",
      "BANKA_TANIM": "AKBANK T.A.Ş.",
      "IADE_TUTAR": 10.99,
      "IADE_TUTAR_PB": "TRY",
      "PC_TUTAR": 0,
      "PC_TUTAR_PB": "",
      "HCEKI": "",
      "KKP_TUTAR": 0,
      "KKP_TUTAR_PB": "",
      "ONAY_KOD": "",
      "ISLENEN_POS": "",
      "VBTYP": "",
      "STATU": 8,
      "STATU_T": "İade Ödeme Hatası",
      "SPRS_ONAY": ""
  },
  {
      "PSS_NO": 5479311701,
      "SIP_TRH": "2022-03-03",
      "FTR_TRH": "2022-03-03",
      "PIS_NO": 5479311701,
      "IADE_TRH": "2022-03-03",
      "MUSAD": "Ömer Tarık Arslantaş",
      "BELGE_TOPL": 10.99,
      "BELGE_TOPL_PB": "TRY",
      "ODEME_TIP": "KKART",
      "ODEME_TIP_T": "Kredi Kartı",
      "BANKA_KODU": "0062",
      "BANKA_TANIM": "TÜRKİYE GARANTİ BANKASI A.Ş.",
      "IADE_TUTAR": 10.99,
      "IADE_TUTAR_PB": "TRY",
      "PC_TUTAR": 0,
      "PC_TUTAR_PB": "",
      "HCEKI": "",
      "KKP_TUTAR": 0,
      "KKP_TUTAR_PB": "",
      "ONAY_KOD": 627858,
      "ISLENEN_POS": "",
      "VBTYP": "",
      "STATU": 6,
      "STATU_T": "Müşteriye Para İadesi Yapıldı. (OK)",
      "SPRS_ONAY": ""
  },
  {
      "PSS_NO": 5479315815,
      "SIP_TRH": "2022-03-31",
      "FTR_TRH": "2022-03-31",
      "PIS_NO": 5479315815,
      "IADE_TRH": "2022-03-31",
      "MUSAD": "Murat kabaklarlı",
      "BELGE_TOPL": 429.89,
      "BELGE_TOPL_PB": "TRY",
      "ODEME_TIP": "KKART",
      "ODEME_TIP_T": "Kredi Kartı",
      "BANKA_KODU": "0062",
      "BANKA_TANIM": "TÜRKİYE GARANTİ BANKASI A.Ş.",
      "IADE_TUTAR": 429.89,
      "IADE_TUTAR_PB": "TRY",
      "PC_TUTAR": 0,
      "PC_TUTAR_PB": "",
      "HCEKI": "",
      "KKP_TUTAR": 0,
      "KKP_TUTAR_PB": "",
      "ONAY_KOD": "212480-2925-authCode",
      "ISLENEN_POS": "",
      "VBTYP": "",
      "STATU": 8,
      "STATU_T": "İade Ödeme Hatası",
      "SPRS_ONAY": ""
  },
  {
      "PSS_NO": 5563536832,
      "SIP_TRH": "2022-03-16",
      "FTR_TRH": "2022-03-16",
      "PIS_NO": 5563536832,
      "IADE_TRH": "2022-03-16",
      "MUSAD": "şevval durmaz",
      "BELGE_TOPL": 109.98,
      "BELGE_TOPL_PB": "TRY",
      "ODEME_TIP": "KKART",
      "ODEME_TIP_T": "Kredi Kartı",
      "BANKA_KODU": "0010",
      "BANKA_TANIM": "TÜRKİYE CUMHURİYETİ ZİRAAT BANKASI A.Ş.",
      "IADE_TUTAR": 109.98,
      "IADE_TUTAR_PB": "TRY",
      "PC_TUTAR": 0,
      "PC_TUTAR_PB": "",
      "HCEKI": "",
      "KKP_TUTAR": 0,
      "KKP_TUTAR_PB": "",
      "ONAY_KOD": 627854,
      "ISLENEN_POS": 1,
      "VBTYP": "",
      "STATU": 6,
      "STATU_T": "Müşteriye Para İadesi Yapıldı. (OK)",
      "SPRS_ONAY": ""
  },
  {
      "PSS_NO": 5479313308,
      "SIP_TRH": "2022-03-11",
      "FTR_TRH": "2022-03-11",
      "PIS_NO": 9792210065,
      "IADE_TRH": "2022-03-11",
      "MUSAD": "Murat kabaklarlı",
      "BELGE_TOPL": 3.25,
      "BELGE_TOPL_PB": "TRY",
      "ODEME_TIP": "KKART",
      "ODEME_TIP_T": "Kredi Kartı",
      "BANKA_KODU": "0062",
      "BANKA_TANIM": "TÜRKİYE GARANTİ BANKASI A.Ş.",
      "IADE_TUTAR": 3.25,
      "IADE_TUTAR_PB": "TRY",
      "PC_TUTAR": 0,
      "PC_TUTAR_PB": "",
      "HCEKI": "",
      "KKP_TUTAR": 0,
      "KKP_TUTAR_PB": "",
      "ONAY_KOD": 153106,
      "ISLENEN_POS": 1,
      "VBTYP": "",
      "STATU": 6,
      "STATU_T": "Müşteriye Para İadesi Yapıldı. (OK)",
      "SPRS_ONAY": ""
  },
  {
      "PSS_NO": 5563538310,
      "SIP_TRH": "2022-04-05",
      "FTR_TRH": "2022-04-05",
      "PIS_NO": 5563538310,
      "IADE_TRH": "2022-04-05",
      "MUSAD": "şevval durmaz",
      "BELGE_TOPL": 216.39,
      "BELGE_TOPL_PB": "TRY",
      "ODEME_TIP": "KKART",
      "ODEME_TIP_T": "Kredi Kartı",
      "BANKA_KODU": "0012",
      "BANKA_TANIM": "TÜRKİYE HALK BANKASI A.Ş.",
      "IADE_TUTAR": 216.39,
      "IADE_TUTAR_PB": "TRY",
      "PC_TUTAR": 0,
      "PC_TUTAR_PB": "",
      "HCEKI": "",
      "KKP_TUTAR": 0,
      "KKP_TUTAR_PB": "",
      "ONAY_KOD": 627853,
      "ISLENEN_POS": "",
      "VBTYP": "",
      "STATU": 6,
      "STATU_T": "Müşteriye Para İadesi Yapıldı. (OK)",
      "SPRS_ONAY": ""
  },
  {
      "PSS_NO": 5563532721,
      "SIP_TRH": "2022-03-30",
      "FTR_TRH": "2022-03-30",
      "PIS_NO": 5563532721,
      "IADE_TRH": "2022-03-30",
      "MUSAD": "Emre KAYA",
      "BELGE_TOPL": 21.89,
      "BELGE_TOPL_PB": "TRY",
      "ODEME_TIP": "KKART",
      "ODEME_TIP_T": "Kredi Kartı",
      "BANKA_KODU": "0015",
      "BANKA_TANIM": "TÜRKİYE VAKIFLAR BANKASI T.A.O.",
      "IADE_TUTAR": 21.89,
      "IADE_TUTAR_PB": "TRY",
      "PC_TUTAR": 0,
      "PC_TUTAR_PB": "",
      "HCEKI": "",
      "KKP_TUTAR": 0,
      "KKP_TUTAR_PB": "",
      "ONAY_KOD": 627854,
      "ISLENEN_POS": 1,
      "VBTYP": "",
      "STATU": 6,
      "STATU_T": "Müşteriye Para İadesi Yapıldı. (OK)",
      "SPRS_ONAY": ""
      },
      {
        "PSS_NO": 5425774401,
        "SIP_TRH": "2022-01-12",
        "FTR_TRH": "2022-01-18",
        "PIS_NO": 7000208805,
        "IADE_TRH": "2022-01-18",
        "MUSAD": "Büşra Test",
        "BELGE_TOPL": 89.97,
        "BELGE_TOPL_PB": "TRY",
        "ODEME_TIP": "HCEKI",
        "ODEME_TIP_T": "Hediye Çeki",
        "BANKA_KODU": "0000",
        "BANKA_TANIM": "",
        "IADE_TUTAR": 0,
        "IADE_TUTAR_PB": "",
        "PC_TUTAR": 89.97,
        "PC_TUTAR_PB": "TRY",
        "HCEKI": "PC0001DW61M130D6A",
        "KKP_TUTAR": 0,
        "KKP_TUTAR_PB": "",
        "ONAY_KOD": "",
        "ISLENEN_POS": "",
        "VBTYP": "K",
        "STATU": 5,
        "STATU_T": "Müşteriye Para İadesi Yapılacak!",
        "SPRS_ONAY": ""
    },
    {
        "PSS_NO": 5440003409,
        "SIP_TRH": "2022-01-05",
        "FTR_TRH": "2022-01-05",
        "PIS_NO": 5440003409,
        "IADE_TRH": "2022-01-05",
        "MUSAD": "Ömer Tarık Arslantaş",
        "BELGE_TOPL": 5.99,
        "BELGE_TOPL_PB": "TRY",
        "ODEME_TIP": "KKART",
        "ODEME_TIP_T": "Kredi Kartı",
        "BANKA_KODU": "0062",
        "BANKA_TANIM": "TÜRKİYE GARANTİ BANKASI A.Ş.",
        "IADE_TUTAR": 5.99,
        "IADE_TUTAR_PB": "TRY",
        "PC_TUTAR": 0,
        "PC_TUTAR_PB": "",
        "HCEKI": "",
        "KKP_TUTAR": 0,
        "KKP_TUTAR_PB": "",
        "ONAY_KOD": "013359-3042-authCode",
        "ISLENEN_POS": "",
        "VBTYP": "",
        "STATU": 8,
        "STATU_T": "İade Ödeme Hatası",
        "SPRS_ONAY": ""
    },
    {
        "PSS_NO": 5440000981,
        "SIP_TRH": "2022-01-12",
        "FTR_TRH": "2022-01-12",
        "PIS_NO": 5440000981,
        "IADE_TRH": "2022-01-12",
        "MUSAD": "Ömer Tarık Arslantaş",
        "BELGE_TOPL": 10.99,
        "BELGE_TOPL_PB": "TRY",
        "ODEME_TIP": "KKART",
        "ODEME_TIP_T": "Kredi Kartı",
        "BANKA_KODU": "0046",
        "BANKA_TANIM": "AKBANK T.A.Ş.",
        "IADE_TUTAR": 10.99,
        "IADE_TUTAR_PB": "TRY",
        "PC_TUTAR": 0,
        "PC_TUTAR_PB": "",
        "HCEKI": "",
        "KKP_TUTAR": 0,
        "KKP_TUTAR_PB": "",
        "ONAY_KOD": "304284-6481-authCode",
        "ISLENEN_POS": "",
        "VBTYP": "",
        "STATU": 8,
        "STATU_T": "İade Ödeme Hatası",
        "SPRS_ONAY": ""
    },
    {
        "PSS_NO": 5440004504,
        "SIP_TRH": "2022-01-12",
        "FTR_TRH": "2022-01-12",
        "PIS_NO": 5440004504,
        "IADE_TRH": "2022-01-12",
        "MUSAD": "Ömer Tarık Arslantaş",
        "BELGE_TOPL": 19.98,
        "BELGE_TOPL_PB": "TRY",
        "ODEME_TIP": "KKART",
        "ODEME_TIP_T": "Kredi Kartı",
        "BANKA_KODU": "0064",
        "BANKA_TANIM": "TÜRKİYE İŞ BANKASI A.Ş.",
        "IADE_TUTAR": 19.98,
        "IADE_TUTAR_PB": "TRY",
        "PC_TUTAR": 0,
        "PC_TUTAR_PB": "",
        "HCEKI": "",
        "KKP_TUTAR": 0,
        "KKP_TUTAR_PB": "",
        "ONAY_KOD": "",
        "ISLENEN_POS": "",
        "VBTYP": "",
        "STATU": 8,
        "STATU_T": "İade Ödeme Hatası",
        "SPRS_ONAY": ""
    },
    {
        "PSS_NO": 5440004506,
        "SIP_TRH": "2022-01-13",
        "FTR_TRH": "2022-01-13",
        "PIS_NO": 5440004506,
        "IADE_TRH": "2022-01-13",
        "MUSAD": "Ömer Tarık Arslantaş",
        "BELGE_TOPL": 10.99,
        "BELGE_TOPL_PB": "TRY",
        "ODEME_TIP": "KKART",
        "ODEME_TIP_T": "Kredi Kartı",
        "BANKA_KODU": "0046",
        "BANKA_TANIM": "AKBANK T.A.Ş.",
        "IADE_TUTAR": 10.99,
        "IADE_TUTAR_PB": "TRY",
        "PC_TUTAR": 0,
        "PC_TUTAR_PB": "",
        "HCEKI": "",
        "KKP_TUTAR": 0,
        "KKP_TUTAR_PB": "",
        "ONAY_KOD": "",
        "ISLENEN_POS": "",
        "VBTYP": "",
        "STATU": 8,
        "STATU_T": "İade Ödeme Hatası",
        "SPRS_ONAY": ""
    },
    {
        "PSS_NO": 5440004619,
        "SIP_TRH": "2022-01-13",
        "FTR_TRH": "2022-01-13",
        "PIS_NO": 5440004619,
        "IADE_TRH": "2022-01-13",
        "MUSAD": "Ömer Tarık Arslantaş",
        "BELGE_TOPL": 24.98,
        "BELGE_TOPL_PB": "TRY",
        "ODEME_TIP": "KKART",
        "ODEME_TIP_T": "Kredi Kartı",
        "BANKA_KODU": "0064",
        "BANKA_TANIM": "TÜRKİYE İŞ BANKASI A.Ş.",
        "IADE_TUTAR": 24.98,
        "IADE_TUTAR_PB": "TRY",
        "PC_TUTAR": 0,
        "PC_TUTAR_PB": "",
        "HCEKI": "",
        "KKP_TUTAR": 0,
        "KKP_TUTAR_PB": "",
        "ONAY_KOD": "",
        "ISLENEN_POS": "",
        "VBTYP": "",
        "STATU": 8,
        "STATU_T": "İade Ödeme Hatası",
        "SPRS_ONAY": ""
    },
    {
        "PSS_NO": 5440006110,
        "SIP_TRH": "2022-01-19",
        "FTR_TRH": "2022-01-19",
        "PIS_NO": 5440006110,
        "IADE_TRH": "2022-01-19",
        "MUSAD": "busra test",
        "BELGE_TOPL": 179.89,
        "BELGE_TOPL_PB": "TRY",
        "ODEME_TIP": "KKART",
        "ODEME_TIP_T": "Kredi Kartı",
        "BANKA_KODU": "0067",
        "BANKA_TANIM": "YAPI VE KREDİ BANKASI A.Ş.",
        "IADE_TUTAR": 179.89,
        "IADE_TUTAR_PB": "TRY",
        "PC_TUTAR": 0,
        "PC_TUTAR_PB": "",
        "HCEKI": "",
        "KKP_TUTAR": 0,
        "KKP_TUTAR_PB": "",
        "ONAY_KOD": "",
        "ISLENEN_POS": "",
        "VBTYP": "",
        "STATU": 8,
        "STATU_T": "İade Ödeme Hatası",
        "SPRS_ONAY": ""
    },
    {
        "PSS_NO": 5440006000,
        "SIP_TRH": "2022-01-31",
        "FTR_TRH": "2022-01-31",
        "PIS_NO": 5440006000,
        "IADE_TRH": "2022-01-31",
        "MUSAD": "Enoca Bilgi Tek ve Dan Ltd Sti",
        "BELGE_TOPL": 24.96,
        "BELGE_TOPL_PB": "TRY",
        "ODEME_TIP": "KKART",
        "ODEME_TIP_T": "Kredi Kartı",
        "BANKA_KODU": "0046",
        "BANKA_TANIM": "AKBANK T.A.Ş.",
        "IADE_TUTAR": 24.96,
        "IADE_TUTAR_PB": "TRY",
        "PC_TUTAR": 0,
        "PC_TUTAR_PB": "",
        "HCEKI": "",
        "KKP_TUTAR": 0,
        "KKP_TUTAR_PB": "",
        "ONAY_KOD": "",
        "ISLENEN_POS": "",
        "VBTYP": "",
        "STATU": 8,
        "STATU_T": "İade Ödeme Hatası",
        "SPRS_ONAY": ""
    },
    {
        "PSS_NO": 5440007701,
        "SIP_TRH": "2022-01-28",
        "FTR_TRH": "2022-01-28",
        "PIS_NO": 5440007701,
        "IADE_TRH": "2022-01-28",
        "MUSAD": "Ömer Tarık Arslantaş",
        "BELGE_TOPL": 10.99,
        "BELGE_TOPL_PB": "TRY",
        "ODEME_TIP": "KKART",
        "ODEME_TIP_T": "Kredi Kartı",
        "BANKA_KODU": "0046",
        "BANKA_TANIM": "AKBANK T.A.Ş.",
        "IADE_TUTAR": 10.99,
        "IADE_TUTAR_PB": "TRY",
        "PC_TUTAR": 0,
        "PC_TUTAR_PB": "",
        "HCEKI": "",
        "KKP_TUTAR": 0,
        "KKP_TUTAR_PB": "",
        "ONAY_KOD": "",
        "ISLENEN_POS": 1,
        "VBTYP": "",
        "STATU": 8,
        "STATU_T": "İade Ödeme Hatası",
        "SPRS_ONAY": ""
      },
      {
        "PSS_NO": 5563540907,
        "SIP_TRH": "2022-05-12",
        "FTR_TRH": "2022-05-12",
        "PIS_NO": 5563540907,
        "IADE_TRH": "2022-05-12",
        "MUSAD": "şevval durmaz",
        "BELGE_TOPL": 87.98,
        "BELGE_TOPL_PB": "TRY",
        "ODEME_TIP": "KKART",
        "ODEME_TIP_T": "Kredi Kartı",
        "BANKA_KODU": "0046",
        "BANKA_TANIM": "AKBANK T.A.Ş.",
        "IADE_TUTAR": 87.98,
        "IADE_TUTAR_PB": "TRY",
        "PC_TUTAR": 0,
        "PC_TUTAR_PB": "",
        "HCEKI": "",
        "KKP_TUTAR": 0,
        "KKP_TUTAR_PB": "",
        "ONAY_KOD": "689560-3102-authCode",
        "ISLENEN_POS": "",
        "VBTYP": "",
        "STATU": 5,
        "STATU_T": "Müşteriye Para İadesi Yapılacak!",
        "SPRS_ONAY": "689560-3102-authCode"
    },
    {
        "PSS_NO": 5563540910,
        "SIP_TRH": "2022-05-12",
        "FTR_TRH": "2022-05-12",
        "PIS_NO": 5563540910,
        "IADE_TRH": "2022-05-12",
        "MUSAD": "şevval durmaz",
        "BELGE_TOPL": 87.98,
        "BELGE_TOPL_PB": "TRY",
        "ODEME_TIP": "KKART",
        "ODEME_TIP_T": "Kredi Kartı",
        "BANKA_KODU": "0046",
        "BANKA_TANIM": "AKBANK T.A.Ş.",
        "IADE_TUTAR": 87.98,
        "IADE_TUTAR_PB": "TRY",
        "PC_TUTAR": 0,
        "PC_TUTAR_PB": "",
        "HCEKI": "",
        "KKP_TUTAR": 0,
        "KKP_TUTAR_PB": "",
        "ONAY_KOD": "314616-7893-authCode",
        "ISLENEN_POS": "",
        "VBTYP": "",
        "STATU": 5,
        "STATU_T": "Müşteriye Para İadesi Yapılacak!",
        "SPRS_ONAY": "314616-7893-authCode"
    },
    {
        "PSS_NO": 5563540913,
        "SIP_TRH": "2022-05-12",
        "FTR_TRH": "2022-05-12",
        "PIS_NO": 5563540913,
        "IADE_TRH": "2022-05-12",
        "MUSAD": "şevval durmaz",
        "BELGE_TOPL": 87.98,
        "BELGE_TOPL_PB": "TRY",
        "ODEME_TIP": "KKART",
        "ODEME_TIP_T": "Kredi Kartı",
        "BANKA_KODU": "0046",
        "BANKA_TANIM": "AKBANK T.A.Ş.",
        "IADE_TUTAR": 87.98,
        "IADE_TUTAR_PB": "TRY",
        "PC_TUTAR": 0,
        "PC_TUTAR_PB": "",
        "HCEKI": "",
        "KKP_TUTAR": 0,
        "KKP_TUTAR_PB": "",
        "ONAY_KOD": "874449-6001-authCode",
        "ISLENEN_POS": "",
        "VBTYP": "",
        "STATU": 5,
        "STATU_T": "Müşteriye Para İadesi Yapılacak!",
        "SPRS_ONAY": "874449-6001-authCode"
    },
    {
        "PSS_NO": 5563540916,
        "SIP_TRH": "2022-05-12",
        "FTR_TRH": "2022-05-12",
        "PIS_NO": 5563540916,
        "IADE_TRH": "2022-05-12",
        "MUSAD": "şevval durmaz",
        "BELGE_TOPL": 87.98,
        "BELGE_TOPL_PB": "TRY",
        "ODEME_TIP": "KKART",
        "ODEME_TIP_T": "Kredi Kartı",
        "BANKA_KODU": "0046",
        "BANKA_TANIM": "AKBANK T.A.Ş.",
        "IADE_TUTAR": 87.98,
        "IADE_TUTAR_PB": "TRY",
        "PC_TUTAR": 0,
        "PC_TUTAR_PB": "",
        "HCEKI": "",
        "KKP_TUTAR": 0,
        "KKP_TUTAR_PB": "",
        "ONAY_KOD": "688537-1440-authCode",
        "ISLENEN_POS": "",
        "VBTYP": "",
        "STATU": 5,
        "STATU_T": "Müşteriye Para İadesi Yapılacak!",
        "SPRS_ONAY": "688537-1440-authCode"
    }

   
]

    


  constructor(private http: HttpClient) { }


    
  getDatas(body: any) {
 
    return this.data;
    
  }

}
