export interface RefundItem {
    PSS_NO: number,
    SIP_TRH: string,
    FTR_TRH: string,
    PIS_NO: number,
    IADE_TRH:string,
    MUSAD: string,
    BELGE_TOPL:number,
    BELGE_TOPL_PB:string,
    ODEME_TIP:string,
    ODEME_TIP_T:string,
    BANKA_KODU: string | number,
    BANKA_TANIM: string,
    IADE_TUTAR:number,
    IADE_TUTAR_PB:string,
    PC_TUTAR: number| string,
    PC_TUTAR_PB:string|null,
    HCEKI:string|null,
    KKP_TUTAR: number,
    KKP_TUTAR_PB:string| null,
    ONAY_KOD: string| null |number ,
    ISLENEN_POS: string| null | number,
    VBTYP: string| null,
    STATU: number,
    STATU_T: string| null,
    SPRS_ONAY:string| null
}