export interface RefundItem {
    PSS_NO: number,
    SIP_TRH: string,
    FTR_TRH: string,
    PIS_NO: number,
    IADE_TRH:string,
    MUSAD: string,
    BELGE_TOPL:number,
    BELGE_TOPL_PB:string,
    ODEME_TIP:string,
    ODEME_TIP_T:string,
    BANKA_KODU: string ,
    BANKA_TANIM: string,
    IADE_TUTAR:number,
    IADE_TUTAR_PB:string,
    PC_TUTAR: string,
    PC_TUTAR_PB:string ,
    HCEKI:string,
    KKP_TUTAR: number,
    KKP_TUTAR_PB:string,
    ONAY_KOD: string ,
    ISLENEN_POS: string,
    VBTYP: string,
    STATU: number,
    STATU_T: string,
    SPRS_ONAY:string
}